### ISSUE TITLE
Bulk export for admins

### ISSUE THREAD

**Issue by driesp** [Chocobozzz/OpenVPN-Admin#10]
Is it possible to get a bulk export of all users by an admin.

**Comment by Chocobozzz** [comment]
You mean an export of all the user configurations or an export of all users (that we could reimport in another OpenVPN-Admin instance for example)?

**Comment by driesp** [comment]
Export all the user configurations. This would be an easy option for system admins

**Comment by SansPseudoFix** [comment]
AH! Told you @Chocobozzz ! :smile_cat:

**Comment by SansPseudoFix** [comment]
Since we have open our eyes, and see that this feature is useless (i.e.: user configurations are same for all, credentiels are for download authorisation), did we rename this issue like: "export of all users"?

**Comment by SansPseudoFix** [comment]
Closed. See #18 :)
