### ISSUE TITLE
./install.sh Error

### ISSUE THREAD

**Issue by TwodoHD** [Chocobozzz/OpenVPN-Admin#100]
Hello,

i get this Error when i write this command `./install.sh www_base_dir web_user web_group`

This is the Qutput:

 `./install.sh www_basedir user group
        base_dir: The place where the web application will be put in
        user:     User of the web application
        group:    Group of the web application
`

How can i fix this Error?

Best regards TwodoHD

**Comment by SansPseudoFix** [comment]
If you use debian and apache, for example:

* ``www_base`` means ``/var/www/html`` **or** ``/var/www/``
*  ``web_user`` and ``web_group`` are ``www-data``

So, you can try ``./install.sh /var/www/html/ www-data www-data``

**Comment by TwodoHD** [comment]
Hello,  

after the installation, the website did not work.  Here the text: 

Can not process this request at this time.

Best regarda TwodoHD
