### ISSUE TITLE
Installation page failed

### ISSUE THREAD

**Issue by hoangminh1109** [Chocobozzz/OpenVPN-Admin#104]
* **PHP version:** PHP 7.0.28
* **MySQL version:** Ver 14.14 Distrib 5.7.22
* **Webserver (Nginx, Apache...):** Apache
* **What is the expected behaviour?** Installation page displayed
* **What do you see instead?** bunch of code appeared
* **PHP logs on pastebin:**

Hello,
I've just installed OpenVPN-Admin on Ubuntu 16.04.
However, after finish, I accessed to installation URL, but the page display a bunch of code.
Please look at attached screenshot.
Would anybody help me?
Thank you.

![openvpn-admin-error](https://user-images.githubusercontent.com/20716428/39438668-eb54695e-4cdf-11e8-9474-383329d634f5.png)

**Comment by kozliatko** [comment]
you have to install php package at first and restart httpd.

**Comment by hoangminh1109** [comment]
I installed php, but not libapache2-mod-php.
After installing libapache2-mod-php, it didn't show up the whole code page, but it ended up with blank page.
There's even nothing when view page source.
I think there's something wrong that php couldn't render the page.
Do you have any idea?

Thank you.
//I'm sorry I couldn't   collect php log.
I checked out and there's nothing in /usr/local/apache/logs/* and /var/log/fpm-php.www.log (enabled in /etc/php/7.0/fpm/pool.d/www.conf and /etc/php/7.0/fpm/php.ini).

**Comment by Chocobozzz** [comment]
This is an issue with your Apache/PHP. Not related to OpenVPN-admin.

Please check on the web, there are plenty resources to install a PHP application behind Apache webserver.
