### ISSUE TITLE
Recover VPN admin password

### ISSUE THREAD

**Issue by diogojesus95** [Chocobozzz/OpenVPN-Admin#107]
* **PHP version:** 5.6.33
* **MySQL version:** mysql  Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (x86_64) using readline 6.3
* **Webserver (Nginx, Apache...):** Apache

Is there a way to recover the admin password? 

Our keypass server recently crashed and we lost a lot of passwords, including the VPN admin password. Since in our company we have remote workers we need to access the logs. Is there a way to recover the password without going into a reinstall? Thank you

**Comment by Chocobozzz** [comment]
No but you could create another admin in the database. We just use native PHP functions for passwords: https://github.com/Chocobozzz/OpenVPN-Admin/blob/master/include/functions.php#L38

**Comment by diogojesus95** [comment]
Sorry for the long time reply, problem fixed now. Thank you so much, had to enter in DB and manually change the admin VPN password.

**Comment by diogojesus95** [comment]
problem fixed. Forgot that after a server restart I had to manually add the iptables
