### ISSUE TITLE
User passwords sometimes change

### ISSUE THREAD

**Issue by driesp** [Chocobozzz/OpenVPN-Admin#11]
User passwords change from time to time (Hash gets a prefix for all users and make the password invallid). Does the same for the admin but this password still works.
![2016-08-30 07_23_18-192 168 0 33_index php_admin](https://cloud.githubusercontent.com/assets/21055722/18077005/aa6917c4-6e82-11e6-8489-24ebddcd1c72.png)

**Comment by Chocobozzz** [comment]
Thanks for reporting this. Can you reproduce with the dev branch?

**Comment by driesp** [comment]
I do not have the dev branch running, only a full deployment in our environment.
