### ISSUE TITLE
install path error

### ISSUE THREAD

**Issue by BluestarCo** [Chocobozzz/OpenVPN-Admin#111]
Hi
 script install ok but i give this
Not Found

The requested URL /index.php was not found on this server.
Apache/2.4.10 (Debian) Server at xxxxx Port 80

when go to http://your-installation/index.php?installation

**Comment by Keikhosro11** [comment]
You have to move the admin /openvpn-admin/ folder to html folder in the www
then you can reach the installation or php file via this address:
http://your-installation/openvpn-admin/index.php?installation
attention that least version of php is 5.6
