### ISSUE TITLE
the archive is either in unknown format or damaged 

### ISSUE THREAD

**Issue by Keikhosro11** [Chocobozzz/OpenVPN-Admin#112]
* **PHP version:** 5.6
* **MySQL version:** Ver 15.1
* **Webserver (Nginx, Apache...):** Apache
Hi, when I download the config file as zip in my system(Windows) I get the "file is corrupted or damaged"
How can I fix?
is this relevant to my server config? what should I do?

**Comment by fardy662** [comment]
download 7z and use that to extract the zip archive https://www.7-zip.org/download.html
