### ISSUE TITLE
Login error after installation

### ISSUE THREAD

**Issue by KasidisMunkongdee** [Chocobozzz/OpenVPN-Admin#115]
I have to finished all install but i cant login with my administrator
How can i fix

**Comment by SansPseudoFix** [comment]
>  How can i fix

By giving us some more explanations? What are these error messages? What is your server OS? Did you correctly follow the instructions?

**Comment by systemD2540** [comment]
Just messages Login error after installtion User-Administrator
I'm running on OS Centos 7 Yeah im follow true instructions But this just login moment

**Comment by systemD2540** [comment]
3 times i try not work for me

**Comment by iziaevich** [comment]
Hi, im try to install on Centos 7 and have same problem. Have only fresh tables on database. No strings with login and password.

**Comment by systemD2540** [comment]
much finding php5.5 is work but openvpn still fail to start

**Comment by systemD2540** [comment]
@iziaevich can you help me ? contact me back on fb. kasidis munkongdee

**Comment by Chocobozzz** [comment]
@systemD2540 please stop spamming

**Comment by systemD2540** [comment]
@Chocobozzz  so sorry im try building all OS but not working

**Comment by iziaevich** [comment]
Solution: install PhP7.1

**Comment by lagman** [comment]
on CentOS 7 take a look at the selinux logs, it doesn't allow running the "login.sh" script by default.
