### ISSUE TITLE
when i finish i get a Login error

### ISSUE THREAD

**Issue by NBSOD** [Chocobozzz/OpenVPN-Admin#118]
* **PHP version:**
PHP 5.4.16 
* **MySQL version:**
mysql  Ver 15.1 Distrib 5.5.56-MariaDB,
* **Webserver (Nginx, Apache...):**
Apache
* **What is the expected behaviour?**

* **What do you see instead?**
nothing wrong
* **PHP logs on pastebin:**
when i visiting http://172.16.13.48/index.php?installation,and i creat a admin-user,then i turn to this page http://172.16.13.48/index.php ,i use the user and password i created,but always warning Login error.what should i do for this error

**Comment by Chocobozzz** [comment]
You need PHP >= 5.5

**Comment by NBSOD** [comment]
。。。very sorry，i will try it，thank you
