### ISSUE TITLE
cant connect to the vpn

### ISSUE THREAD

**Issue by faglo** [Chocobozzz/OpenVPN-Admin#119]
why i cant connecxt to the vpn?

Fri Aug 03 18:48:48 2018 MANAGEMENT: >STATE:1533311328,TCP_CONNECT,,,,,,
Fri Aug 03 18:50:48 2018 TCP: connect to [AF_INET]94.142.1 failed: Unknown error

client
dev tun
proto tcp-client
remote 94.14
resolv-retry infinite
cipher AES-256-CBC
redirect-gateway

# Keys
# Identity
ca ca.crt
tls-auth ta.key 1
key-direction 1
remote-cert-tls server
auth-user-pass
auth-nocache

# Security
nobind
persist-key
persist-tun
comp-lzo
verb 3

# Proxy ?
# http-proxy cache.univ.fr 3128

**Comment by lagman** [comment]
What distro are you using?
what is the server configs?
what are the log outputs?
