### ISSUE TITLE
Instalation Issue

### ISSUE THREAD

**Issue by matthewric** [Chocobozzz/OpenVPN-Admin#125]
Trying to install I get this easyrsa and openvpn are installed any ideas anyone

################## Creating the certificates ##################
tar: EasyRSA-3.0.5.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat 'EasyRSA-3.0.5': No such file or directory
rm: cannot remove 'EasyRSA-3.0.5.tgz': No such file or directory
./install.sh: line 133: cd: /etc/openvpn/easy-rsa: No such file or directory
./install.sh: line 167: ./easyrsa: No such file or directory
./install.sh: line 168: ./easyrsa: No such file or directory
./install.sh: line 170: ./easyrsa: No such file or directory
./install.sh: line 172: ./easyrsa: No such file or directory
Sun Oct 21 19:21:22 2018 Cannot open shared secret file 'pki/ta.key' for write: No such file or directory (errno=2)
Sun Oct 21 19:21:22 2018 Exiting due to fatal error

**Comment by qqqasdwx** [comment]
easyRSA change release name 
![image](https://user-images.githubusercontent.com/19298463/47270822-db464080-d5a3-11e8-85b4-4e84517d889b.png)
change your `install.sh` line 129 ,try it!

**Comment by matthewric** [comment]
Did exactly the same when I changed it to 3.0.4

**Comment by lagman** [comment]
hi
take a look at this 
https://github.com/Chocobozzz/OpenVPN-Admin/pull/126/commits/53c86567475ff02ab96ac90986c2700ecf4a7a70
and this 
https://github.com/Chocobozzz/OpenVPN-Admin/pull/126/commits/c7eef1ec95f3ade5d3e2ebf4219e837068782f2d
it should fix your problem

**Comment by lagman** [comment]
The file was probably there from previous installation. What distro are you using?
are you using cenotOS 7 or debian based?
what does openvpn and system logs say?

**Comment by lagman** [comment]
Check to see if it connects to mysql?
Look at openvpn and system logs.
What distro are you using?

**Comment by matthewric** [comment]
I removed openvpn deleted the dir and uninstalled open admin 
then reinstalled everything
doesn't appear to be binding to a port and this is my log

Options error: Unrecognized option or missing parameter(s) in /etc/openvpn/server.conf:83: verify-client-cert (2.3.10)
Use --help for more information.

**Comment by lagman** [comment]
could you print your /etc/openvpn/server.conf

**Comment by matthewric** [comment]
## GENERAL ##

# TCP or UDP, port 1194, tunneling
mode server
proto udp
port 1194
dev tun

## KEY, CERTS AND NETWORK CONFIGURATION ##
# Identity
ca ca.crt
# Public key
cert server.crt
# Private key
key server.key
# Symmetric encryption
dh dh.pem
# Improve security (DDOS, port flooding...)
# 0 for the server, 1 for the client
tls-auth ta.key 0
# Encryption protocol
cipher AES-256-CBC

# Network
# Subnetwork, the server will be the 10.8.0.1 and clients will take the other ips
server 10.8.0.0 255.255.255.0

# Redirect all IP network traffic originating on client machines to pass through the OpenVPN server
push "redirect-gateway def1"

# Alternatives DNS (FDN)
push "dhcp-option DNS 80.67.169.12"
push "dhcp-option DNS 80.67.169.40"

# (OpenDNS)
# push "dhcp-option DNS 208.67.222.222"
# push "dhcp-option DNS 208.67.220.220"

# (Google)
# push "dhcp-option DNS 8.8.8.8"
# push "dhcp-option DNS 8.8.4.4"

# Ping every 10 seconds and if after 120 seconds the client doesn't respond we disconnect
keepalive 10 120
# Regenerate key each 5 hours (disconnect the client)
reneg-sec 18000

## SECURITY ##

# Downgrade privileges of the daemon
user nobody
group nogroup

# Persist keys (because we are nobody, so we couldn't read them again)
persist-key
# Don't close and re open TUN/TAP device
persist-tun
# Enable compression
comp-lzo

## LOG ##

# Verbosity
# 3/4 for a normal utilisation
verb 3
# Max 20 messages of the same category
mute 20
# Log gile where we put the clients status
status openvpn-status.log
# Log file
log-append /var/log/openvpn.log
# Configuration directory of the clients
client-config-dir ccd

## PASS ##

# Allow running external scripts with password in ENV variables
script-security 3

# Use the authenticated username as the common name, rather than the common name from the client cert
username-as-common-name
# Client certificate is not required 
client-cert-not-required
# Use the connection script when a user wants to login
auth-user-pass-verify scripts/login.sh via-env
# Maximum of clients
max-clients 50
# Run this scripts when the client connects/disconnects
client-connect scripts/connect.sh
client-disconnect scripts/disconnect.sh

**Comment by lagman** [comment]
change this line auth-user-pass-verify scripts/login.sh via-env
to this
auth-user-pass-verify "scripts/login.sh" via-env

**Comment by matthewric** [comment]
Did that still not working it's like the server is running but not running i still cant find an open port for it

**Comment by lagman** [comment]
Ehat does system log and openvpn log say

**Comment by seboss666** [comment]
Just to mention, for 3.0.6 they again changed the file naming scheme. You need to modify with : 

`wget https://github.com/OpenVPN/easy-rsa/releases/download/v${EASYRSA_LATEST}/EasyRSA-unix-v${EASYRSA_LATEST}.tgz`

As I was in a rush to install it on a centos-based system, I commented the installation, install the easyrsa package from epel, and copy the 3.0.3 folder to /etc/openvpn/easy-rsa destination.

**Comment by Chocobozzz** [comment]
:rage:

**Comment by Chocobozzz** [comment]
Thanks @seboss666 

Should be fixed by https://github.com/Chocobozzz/OpenVPN-Admin/commit/c193f3e0e22b6be8f152f1fa6bb3e13a80fc7db5
