### ISSUE TITLE
Missing </tls-auth> at the end of client.ovpn

### ISSUE THREAD

**Issue by cnmicha** [Chocobozzz/OpenVPN-Admin#137]
* **PHP version:** PHP 7.3.3-1+0\~20190307202245.32+stretch~1.gbp32ebb2 (cli) (built: Mar  7 2019 20:22:46) ( NTS )
* **MySQL version:** mysql  Ver 15.1 Distrib 10.3.13-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* **Webserver (Nginx, Apache...):** nginx/1.10.3
* **What is the expected behaviour?** On the website, the user enters its credentials and selects "GNU/Linux". A client.ovpn file is created (inside the zip file) that is parsed by `sudo openvpn --config client.ovpn`.
* **What do you see instead?** In the client.ovpn file, the `</tls-auth>` tag is missing at the very end of the file, making OpenVPN fail to connect.

* **Client OS:** Ubuntu 18.04.2 LTS, using OpenVPN 2.4.4 x86_64-pc-linux-gnu

**Comment by Chocobozzz** [comment]
Thanks @cnmicha, should be fixed by https://github.com/Chocobozzz/OpenVPN-Admin/commit/2e4643d5cfea9cc211e90fa87f5c1305e719c817 :)
