### ISSUE TITLE
HELP install

### ISSUE THREAD

**Issue by hostingfuze** [Chocobozzz/OpenVPN-Admin#138]
NOT WORKING !!!

- error intall
- error configure 
- incomplete tutorial !

**Comment by hostingfuze** [comment]
workrking 
useradd www-data !

**Comment by Chocobozzz** [comment]
you're welcome

**Comment by hostingfuze** [comment]
not working in Centos 7 (KVM Virtualizor)

Working in debian 9 , good job !
