### ISSUE TITLE
can't enable a user after disabling it

### ISSUE THREAD

**Issue by olaulau** [Chocobozzz/OpenVPN-Admin#141]
* **PHP version:**
7.0, 7.2
* **MySQL version:**
5.7.25-0ubuntu0.18.10.2
* **Webserver (Nginx, Apache...):**
apache
* **What is the expected behaviour?**
checking enable re-enables the user, and the checkbox stays enabled
* **What do you see instead?**
checkbox stays disabled, and the user cannot connect the VPN anymore
* **PHP logs on pastebin:**
nothing special in logs :-/

**Comment by merlin-tc** [comment]
Having the same problem.
Running php7.2 with nginx.

**Comment by jozefrebjak** [comment]
I have this problem too, is there some solution ? thanks

**Comment by sky-daiji** [comment]
哈哈哈哈哈,   this problem is so easy,I I solved the problem.

**Comment by rombtr** [comment]
How to fix this problem sky-daiji ?

**Comment by GiannisRallis** [comment]
> 哈哈哈哈哈, this problem is so easy,I I solved the problem.

Hello, can you please show us the way to make this work?

**Comment by GiannisRallis** [comment]
https://github.com/Chocobozzz/OpenVPN-Admin/pull/153/files

Fixed!
