### ISSUE TITLE
question:  Someone has tried migrating to Debian 10 (Buster)?

### ISSUE THREAD

**Issue by alfredopons** [Chocobozzz/OpenVPN-Admin#151]
For Debian 10:

Mariadb or  [Mysql](https://tecadmin.net/install-mysql-on-debian-10-buster/) ?
Nodejs 11 or 12?

Thanks.

**Comment by v1ru535** [comment]
I've tested with Debian 10, results are OK.

But remember to set 
```script-security 3```
in "server.conf" file, without that:
```
WARNING: External program may not be called unless '--script-security 2' or higher is enabled. See --help text or man page for detailed info.
WARNING: Failed running command (--auth-user-pass-verify): external program fork failed
```

o/
