### ISSUE TITLE
More people working on the project!

### ISSUE THREAD

**Issue by driesp** [Chocobozzz/OpenVPN-Admin#16]
There are more people working on the project, maybe it is adviced to start using a stylesheet or something.
Maybe it is also advices to use Hipchat so collaboration is much easier

**Comment by Chocobozzz** [comment]
:+1:

A styleguide for PHP/Shell at least.

For the collaboration, maybe we could use IRC (`#openvpn-admin` on Freenode for example). I don't really like closed source chat softwares (Slack, Hipchat, Gitter...).

**Comment by driesp** [comment]
i'm all open for that (haha no pun intended)
