### ISSUE TITLE
How can I install the ovpn in iPhone IOS?

### ISSUE THREAD

**Issue by vicn1222** [Chocobozzz/OpenVPN-Admin#169]
I download the configuration, unzip, and it gives 4 files

ca.crt  
ta.key  
client.ovpn  
update-resolv.sh

The OpenVPN Connect in iPhone only take client.ovpn. Under Certificate, I can't select anything. It always show "None"... I am unable to connect... 

Please help. Thanks

**Comment by Wutze** [comment]
https://github.com/Wutze/OpenVPN-WebAdmin#openvpn-clients-and-documentation-to-install

**Comment by vicn1222** [comment]
Thanks. Got it work finally. 

There is one problem though. My website and openvpn are installed in the same machine with same ip address. When I turn on vpn, the website still see the original ip. It doesn't mask the ip in this case. What should I do then?

**Comment by Wutze** [comment]
Unfortunately, I cannot say anything about this without information about the routing or the firewall rules. Normally, you should not use both together on one server.

**Comment by vicn1222** [comment]
All works now! Thanks
