### ISSUE TITLE
Installation : bower invalid-meta

### ISSUE THREAD

**Issue by Zatalyz** [Chocobozzz/OpenVPN-Admin#22]
Je viens de faire l'installation sous debian jessie, sur une vps d'ovh (noyau pas vraiment à jour, donc...).

Une seule erreur répertoriée lors de l'installation :
`bower invalid-meta  The "main" field cannot contain minified files`

Cela n'a rien bloqué ; par contre, une fois l'installation finie, il manque le css dans l'application. Je devrais pouvoir trouver ça pour ma propre installation (mais j'accepte avec plaisir qu'on me pointe ce qu'il faut chercher !) mais il y a peut-être une erreur de syntaxe dans un des fichier d'installation ? C'est mineur mais si ça peut aider à améliorer...

Merci pour cet outil, c'est une super idée.

**Comment by Chocobozzz** [comment]
Merci pour le report.

Dans le dossier web (cible de l'installation donc), est ce qu'il y a le dossier `vendor` contenant les différentes librairies d'OpenVPN-Admin (Bootstrap, Bootstrap table...) ?

Si non, peux tu donner la sortie de bower (via gist ou pastebin) ? Tu peux l'avoir en utilisant le script `./update.sh`.
Si oui, as-tu bien configuré ton serveur web ?

**Comment by SansPseudoFix** [comment]
> Cela n'a rien bloqué ; par contre, une fois l'installation finie, il manque le css dans l'application. Je devrais pouvoir trouver ça pour ma propre installation (mais j'accepte avec plaisir qu'on me pointe ce qu'il faut chercher !)

Normalement, en éditant le fichier [index.php](https://github.com/Chocobozzz/OpenVPN-Admin/blob/master/index.php#L97) et en enlevant le ``/`` devant ``vendor`` et ``css``, ça devrait fonctionner (avec un coup de ``./update.sh``après).

**Comment by SansPseudoFix** [comment]
J'ai fait un commit avec ces changements, je testerai en prod d'ici peu. Il faudrait aussi des testeurs utilisant nginx et autres pour être sûr que ça ne casse rien non plus.

**Comment by SansPseudoFix** [comment]
`` bower invalid-meta The "main" field cannot contain minified files`` is just a warning, so we can ignore it.

Some graphical issues (no CSS nor JS loaded) was linked by ``\`` in front of scripts path: fix by https://github.com/Chocobozzz/OpenVPN-Admin/commit/a235809290771276f7bc63d3a3c6e0f3e6059e9e.

**Comment by SansPseudoFix** [comment]
``bower invalid-meta The "main"`` n'est qu'un message de mise en garde, on peut l'ignorer sans soucis.

Les soucis avec le CSS et JS devraient être résolus avec https://github.com/Chocobozzz/OpenVPN-Admin/commit/a235809290771276f7bc63d3a3c6e0f3e6059e9e.
