### ISSUE TITLE
Can't create users.

### ISSUE THREAD

**Issue by driesp** [Chocobozzz/OpenVPN-Admin#23]
When trying to create users with the new 0.3.0 version i always get the the following popup error:error.
Digging in my apache logs I get these errors.
![img_20160915_163753](https://cloud.githubusercontent.com/assets/21055722/18554231/d4305fd4-7b63-11e6-8cd7-edef3514bde3.jpg)
@Chocobozzz can you have a look at this. (Even tried it with a complete reinstall.)

**Comment by SansPseudoFix** [comment]
Seems like you haven't any ``openvpn-admin`` database. Can you verify this statement (``mysql -u root -p -e "use openvpn-admin; show tables;"``)?

**Comment by driesp** [comment]
The table was not during installation or after installation. There is also (when you create a user) a value given with a start time and a stop time. But in the sql statement you tell it to not be null but in the code you send a null value. finding that gave me a headache :(

**Comment by Chocobozzz** [comment]
@driesp It's seems you forgot the [last installation step](https://github.com/Chocobozzz/OpenVPN-Admin#installation) that creates the MySQL tables.
I don't unserstand how you could log in as an administrator without the admin table.

For the SQL statement it's not a big issue because the `null` will be converted to `0000-00-00` in MySQL.

**Comment by driesp** [comment]
it did install the admin table. after i went to the index.php?installation But with that admin tables I got some errors on both the log and user table. I resolved this by changing the `0000-00-00` to `1970-01-01`

**Comment by Chocobozzz** [comment]
You're not supposed to install the admin table yourself. It is made automatically by `index.php?installation`.

**Comment by driesp** [comment]
The log and user table wouldn't install automatically. They couldn't install due to error's I was getting. I had to adapt the sql file and then install the log and user tables because the system didn't install them in the right way

**Comment by valantislevas** [comment]
also after setup when i tried to make a admin or login on web i cant..  blank screen :/
can someone help me?

**Comment by valantislevas** [comment]
if manually put admin_id and password with md5 after press login "page isn’t working"
what i must do?

**Comment by valantislevas** [comment]
PHP Fatal error:  Call to undefined function password_hash() in /var/www/openvpn-admin/include/functions.php on line 22, referer: http://myserver.com/openvpn-admin/index.php?installation

**Comment by Chocobozzz** [comment]
@valantislevas You need PHP >=  5.5.0

https://secure.php.net/manual/fr/function.password-hash.php
