### ISSUE TITLE
how to connect without password

### ISSUE THREAD

**Issue by DenJohX** [Chocobozzz/OpenVPN-Admin#25]
I'm using a linux client. Using the downloaded configuration file and enabling it as a service (using it from /etc/openvpn on startup) it asks for the password during the startup process.

Is there a way to not ask for the password?, It cannot be used as a background service if it asks for it.

**Comment by SansPseudoFix** [comment]
You mean that you don't use GUI? If so, you can easily save your password.

If you're using CLI, you can do:

* create ``auth.txt`` in ``/etc/openvpn/``
* add 2 lines:
 * username
 * password
* save
* edit ``/etc/openvpn/client.conf``
* change ``auth-user-pass`` to ``auth-user-pass auth.txt``

Should be good.

**Comment by DenJohX** [comment]
@SansPseudoFix 
Thanks, I will try it.
