### ISSUE TITLE
Installation sur ArchLinux

### ISSUE THREAD

**Issue by yapbreak** [Chocobozzz/OpenVPN-Admin#3]
Bonjour,
Je viens d’installer OpenVPN-Admin sur mon Archlinux sans gros problème. Tout se passe bien. J’ai juste 2 petites remarques :

- le port part défaut dans server.conf est 443… C’est un peu étrange car le port par défaut d’openvpn est 1194 et que le port 443 est déjà occupé par le serveur ssl (quand on installe openvpn et openvpn-admin sur la même machine par exemple)
- l’autre remarque vient plus de l’OS, sous Archlinux, on n’a pas de nogroup mais on a le group nobody, ce n’est qu’une question de nommage, mais quitte à vérifier plein de chose dans le script install.sh, pourquoi ne pas vérifier ça aussi…

Dans tous les cas, ça faisait un moment que je voulais installer et configurer OpenVpn sur mon serveur et après plusieurs tentatives infructueuses, j’avais laissé tomber… Mais là, en 10 minutes, tout fonctionne, chapeau !

Au passage, la configuration GNU/Linux fonctionne aussi sous Android (testé avec l’application "OpenVPN for Android" https://f-droid.org/repository/browse/?fdfilter=OpenVPN+for+Android&fdid=de.blinkt.openvpn)

**Comment by Chocobozzz** [comment]
Bonjour,

    * Le port 443 est un choix arbitraire afin de passer outre les pare-feu potentiels. Pour ton soucis tu peux utiliser la directive `port-share` sur le serveur OpenVPN (http://www.vpntutorials.com/tutorials/openvpn-sharing-a-port-with-a-webserver-on-port-80-443/) qui te permettra d'avoir un Openvpn sur le port 443 tout en ayant un serveur web écoutant en SSL (que l'utilisateur pourra aussi accéder via le port 443).
    * Bien vu, il faudra que je modifie ça. Je ferme l'issue et en recrée une pour ce besoin spécifique.

Merci beaucoup, ça fait plaisir et c'est bon de savoir que ça fonctionne sous Arch' (mis à part le soucis de groupe) et Android :)

Par contre la prochaine fois si tu peux rédiger l'issue en anglais, ce sera appréciable afin que tout le monde puisse profiter de la conversation ;)

**Comment by yapbreak** [comment]
I did not know about port-share directive… I will try it today and I hope it will work against my sslh installation.
Thank you.

**Comment by yapbreak** [comment]
So finally, no need of port-share since OpenVPN is natively supported by sslh!
Everything seems to be work.

**Comment by SansPseudoFix** [comment]
Hi @yapbreak 
I'm trying to use same app than you for android, but it doesn't work (and logs are not revelants) =/
Did it works out of the box for you, or have you done some hacks?

**Comment by yapbreak** [comment]
Yes, everything works out of the box. When I imported configuration in my android device, I just change the port to use 1194 I defined on my server and then the application asked me where are both ca.crt and ta.crt. After selecting them in a file browser, it was OK. And now I use it almost every day...

**Comment by SansPseudoFix** [comment]
Mh, weird. My crt and key are automatically import, but doesn't work. Thx anyway, I will investigate :)
