### ISSUE TITLE
openvpn files configuration of user corrupt

### ISSUE THREAD

**Issue by valantislevas** [Chocobozzz/OpenVPN-Admin#30]
after succesfully installation when i tried to download the configuration files it says that file is corrupt..

**Comment by SansPseudoFix** [comment]
Can you be more specific? What's your OS? Are you using a GUI client or CLI?

**Comment by valantislevas** [comment]
i fixed now need to be www-data on webfiles on debian 7 ..
i also get the files and tried to login it asks user/pass i put it but i get reconnect 

Fri Dec 09 11:32:39 2016 TCP: connect to [AF_INET]MYIPPPPPPPPPPPP:1194 failed, will try again in 5 seconds: Connection timed out (WSAETIMEDOUT)
Fri Dec 09 11:32:39 2016 SIGUSR1[soft,init_instance] received, process restarting
Fri Dec 09 11:32:39 2016 MANAGEMENT: >STATE:1481275959,RECONNECTING,init_instance,,
Fri Dec 09 11:32:39 2016 Restart pause, 5 second(s)

i am searching the solution of that problem

i see that prot i left "443" and it tryes to connect 1194.. maybe i reinstall it..

**Comment by valantislevas** [comment]
i tried but nothing my log

> Fri Dec 09 12:04:54 2016 TCP: connect to [AF_INET]IPPPPPPPPPPPADRESS:1194 failed, will try again in 5 seconds: Connection timed out (WSAETIMEDOUT)
> Fri Dec 09 12:04:54 2016 SIGUSR1[soft,init_instance] received, process restarting
> Fri Dec 09 12:04:54 2016 MANAGEMENT: >STATE:1481277894,RECONNECTING,init_instance,,
> Fri Dec 09 12:04:54 2016 Restart pause, 5 second(s)
> Fri Dec 09 12:04:57 2016 SIGTERM[hard,init_instance] received, process exiting
> Fri Dec 09 12:04:57 2016 MANAGEMENT: >STATE:1481277897,EXITING,init_instance,,

**Comment by SansPseudoFix** [comment]
@valantislevas any news?
Check if your client configuration matches with your server configuration (e.g: port 443 -> port 443)
