### ISSUE TITLE
Error reading multiple files by profil  ca.crt ta.key

### ISSUE THREAD

**Issue by arobase13** [Chocobozzz/OpenVPN-Admin#32]
Hello I installed the script yesterday on my VPS Apache installation and openvpn all fresh. But I download the configuration file of the first user and I import it into OpenVPN Connect on Android I have this error message. What can this be? Knowing that I have configured Apache to use HTTPS forcibly and that I generate certificates with let's encrypt

**Comment by Chocobozzz** [comment]
Can you test from OpenVPN on a computer or with this application? https://f-droid.org/repository/browse/?fdfilter=vpn&fdid=de.blinkt.openvpn

**Comment by arobase13** [comment]
Hello thank you for your answer I had already tested with this application this morning I try again at the moment I you like the error messages


13:13 Used x 1 tries to get current version (5/5) of the profile
13:13 Options error: --ca fails with 'ca.crt': No such file or directory
13:13 Options error: Please correct these errors.

**Comment by SansPseudoFix** [comment]
If I remember correctly, you have to manually set up your configuration (e.g: manually add ``ca.crt`` and ``ta.key``) with OpenVPN for Android.

For OpenVPN Connect, did you see [this](https://forums.openvpn.net/viewtopic.php?t=12738)?

**Comment by arobase13** [comment]
Ok I had not seen, but the configuration file I downloaded was in ZIP format and it did not contain any .CRT files or .KEY files, so I have to go manually to find them on the server

**Comment by Chocobozzz** [comment]
The zip file should contain a directory in which there are `ca.crt`, `ta.key` and `client.conf`.

Try to see your error logs to find why your zip file is empty.

**Comment by arobase13** [comment]
I downloaded both versions available the Windows version that contains only a ovpn file and the Linux file that contains a .conf file and .sh file.

Where can I check logs?

**Comment by SansPseudoFix** [comment]
> Where can I check logs?

You have one: ``/var/log/openvpn.log`` and for your web interface, depends of your vhost configuration.

**Comment by arobase13** [comment]
Options error: --dh fails with 'dh.pem': No such file or directory
Options error: --ca fails with 'ca.crt': No such file or directory
Options error: --cert fails with 'server.crt': No such file or directory
Options error: --key fails with 'server.key': No such file or directory
Options error: --tls-auth fails with 'ta.key': No such file or directory
Options error: Please correct these errors.
Use --help for more information.
Options error: --dh fails with 'dh.pem': No such file or directory
Options error: --ca fails with 'ca.crt': No such file or directory
Options error: --cert fails with 'server.crt': No such file or directory
Options error: --key fails with 'server.key': No such file or directory
Options error: --tls-auth fails with 'ta.key': No such file or directory
Options error: Please correct these errors.
Use --help for more information.
Options error: --dh fails with 'dh.pem': No such file or directory
Options error: --ca fails with 'ca.crt': No such file or directory
Options error: --cert fails with 'server.crt': No such file or directory
Options error: --key fails with 'server.key': No such file or directory
Options error: --tls-auth fails with 'ta.key': No such file or directory
Options error: Please correct these errors.
Use --help for more information.
Options error: --dh fails with 'dh.pem': No such file or directory
Options error: --ca fails with 'ca.crt': No such file or directory
Options error: --cert fails with 'server.crt': No such file or directory
Options error: --key fails with 'server.key': No such file or directory
Options error: --tls-auth fails with 'ta.key': No such file or directory
Options error: Please correct these errors.
Use --help for more information.

**Comment by Chocobozzz** [comment]
Okay, your installation has probably failed and the keys have not been created. Try to reinstall and see if you have errors at the keys generation step.

**Comment by arobase13** [comment]
I just reinstall the script or just openVPN

**Comment by Chocobozzz** [comment]
The script.

**Comment by arobase13** [comment]
################## Creating the certificates ##################
./install.sh: line 119: curl: command not found
tar: EasyRSA-.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat 'EasyRSA-': No such file or directory
rm: cannot remove 'EasyRSA-.tgz': No such file or directory
./install.sh: line 126: cd: /etc/openvpn/easy-rsa: No such file or directory
./install.sh: line 160: ./easyrsa: No such file or directory
./install.sh: line 161: ./easyrsa: No such file or directory
./install.sh: line 163: ./easyrsa: No such file or directory
./install.sh: line 165: ./easyrsa: No such file or directory
Tue Jan  3 11:49:57 2017 Cannot open shared secret file 'pki/ta.key' for write:No such file or directory (errno=2)
Tue Jan  3 11:49:57 2017 Exiting due to fatal error

################## Setup OpenVPN ##################
cp: cannot stat '/etc/openvpn/easy-rsa/pki/ca.crt': No such file or directory
cp: cannot stat '/etc/openvpn/easy-rsa/pki/ta.key': No such file or directory
cp: cannot stat '/etc/openvpn/easy-rsa/pki/issued/server.crt': No such file or irectory
cp: cannot stat '/etc/openvpn/easy-rsa/pki/private/server.key': No such file ordirectory
cp: cannot stat '/etc/openvpn/easy-rsa/pki/dh.pem': No such file or directory

################## Setup firewall ##################

################## Setup MySQL database ##################

################## Setup web application ##################
cp: cannot stat '/etc/openvpn/ca.crt': No such file or directory
cp: cannot stat '/etc/openvpn/ta.key': No such file or directory
cp: cannot stat '/etc/openvpn/ca.crt': No such file or directory
cp: cannot stat '/etc/openvpn/ta.key': No such file or directory

**Comment by arobase13** [comment]
oops, ./install.sh: line 119: curl: command not found

apt-get install curl

**Comment by Chocobozzz** [comment]
So you just don't have `curl` installed. Please follow the install guide: https://github.com/Chocobozzz/OpenVPN-Admin#debian-jessie

EDIT: yep :)
