### ISSUE TITLE
no internet connection

### ISSUE THREAD

**Issue by arobase13** [Chocobozzz/OpenVPN-Admin#33]
Hello, I did not have time yesterday to say thank you for the help given to the previous problem (closed topic). But I am faced with another problem, the application connects well to the vpn, but there seems to be no internet connection, I looked on various forums, I explore all the tracks, without success for the moment . I am French, I hope my English is not too bad. Have a good day and a happy new year at all.

**Comment by SansPseudoFix** [comment]
> Hello, I did not have time yesterday to say thank you for the help given to the previous problem (closed topic).

You're welocome, but you can add comment on a closed issue ;)

> But I am faced with another problem, the application connects well to the vpn, but there seems to be no internet connection, I looked on various forums, I explore all the tracks, without success for the moment .

Is OpenVPN server is running? -> ``systemctl status openvpn@server``
Have you reboot your server without saving your iptables rules? Try:

````
iptables -I FORWARD -i tun0 -j ACCEPT
iptables -I FORWARD -o tun0 -j ACCEPT
iptables -I OUTPUT -o tun0 -j ACCEPT

iptables -A FORWARD -i tun0 -o eth0 -j ACCEPT
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
iptables -t nat -A POSTROUTING -s 10.8.0.2/24 -o eth0 -j MASQUERADE
````

Something in your logs?

> I am French, I hope my English is not too bad. Have a good day and a happy new year at all.

It's ok, @Chocobozzz and I are french too ;)

**Comment by arobase13** [comment]
Hello, thank you for the answer, I proceeded to several reinstallation of the whole server, still no internet, after I am forced to say that I maitrise not iptables.
I installed iptables-persistent.
I'll see the log

**Comment by arobase13** [comment]
log 

`Wed Jan  4 16:52:40 2017 80.215.109.90:26413 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jan  4 16:52:40 2017 80.215.109.90:26413 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Wed Jan  4 16:52:40 2017 80.215.109.90:26413 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jan  4 16:52:40 2017 80.215.109.90:26413 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA
Wed Jan  4 16:52:40 2017 80.215.109.90:26413 [arobase] Peer Connection Initiated with [AF_INET]80.215.109.90:26413
Wed Jan  4 16:52:40 2017 arobase/80.215.109.90:26413 MULTI_sva: pool returned IPv4=10.8.0.6, IPv6=(Not enabled)
Wed Jan  4 16:52:40 2017 arobase/80.215.109.90:26413 OPTIONS IMPORT: reading client specific options from: /tmp/openvpn_cc_b029048dc7876da5075518c0a2fd5ea7.tmp
Wed Jan  4 16:52:40 2017 arobase/80.215.109.90:26413 MULTI: Learn: 10.8.0.6 -> arobase/80.215.109.90:26413
Wed Jan  4 16:52:40 2017 arobase/80.215.109.90:26413 MULTI: primary virtual IP for arobase/80.215.109.90:26413: 10.8.0.6
Wed Jan  4 16:52:41 2017 arobase/80.215.109.90:26413 PUSH: Received control message: 'PUSH_REQUEST'
Wed Jan  4 16:52:41 2017 arobase/80.215.109.90:26413 send_push_reply(): safe_cap=940
@                 `

**Comment by SansPseudoFix** [comment]
I don't see any errors in your logs, I'm out of ideas. If you want, I wrote a [blog post in french](https://sanspseudofix.fr/openvpn-admin-0.3.0-est-sorti-couvert-bien-sur/) (for Debian Jessie), maybe you have missed a step.

**Comment by arobase13** [comment]
158/5000
I switch the server under Ubuntu, no way to install openvpn, back under Debian 8, everything is installed, but no internet access on the clients, weird.

**Comment by SansPseudoFix** [comment]
On what OS is your client? What's your desktop environment? Gnome, KDE, XFCE, other? Did you check if your client configuration is correct (correct port, correct ca or key etc)? Any proxy/firewall rules on your client desktop?

**Comment by arobase13** [comment]
I just removed the script to test, I changed nothing to openvpn, I just installed openvpn as, and I managed to connect to my vpn, I have access to the internet.

Config test, KUbuntu 16.10 as well as Windows 7 with openvpn connect, ditto with Android 6 with two different app.

I do not want to stay with openvpn as, I want to reinstall the script, but some thing must go wrong.

But what ?

**Comment by arobase13** [comment]
Hello, I changed server provider, the problem is resolved.
Script installed in seconds and I have internet.

On the other hand do you have connection utility for Windows to offer me? I find the client openvpn windows complicated.

**Comment by driesp** [comment]
@arobase13 I use TunXten on Windows. Works like a charm. But I'm also gonna write a custom connection Client.
