### ISSUE TITLE
DB creation error during installation

### ISSUE THREAD

**Issue by stex79** [Chocobozzz/OpenVPN-Admin#35]
Hi,

I discovered that using a recent Ubuntu 16.04 with mysql 5.7 the installation script fails to create log and user table.

This is due to the usage of the default value in the log table for the field log_end_time.

To make it work I changed import.sql for this field to be:
`log_end_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01',

Regards

**Comment by stex79** [comment]
Also the file include/grids.php need to have the default values at lines 122 and 123 because 0000-00-00 in not accepted.

Regards

**Comment by Chocobozzz** [comment]
Hi thanks for reporting this @stex79 

Do you want to make a pull request?

**Comment by Chocobozzz** [comment]
Should be fixed with version 0.3.2. Thanks!
