### ISSUE TITLE
openvpn got AUTH_FAILED message

### ISSUE THREAD

**Issue by wackejohn** [Chocobozzz/OpenVPN-Admin#38]
got  ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13)
Any idea?Thanks.

**Comment by Chocobozzz** [comment]
Check mysql is started and correctly configured: http://stackoverflow.com/questions/5376427/cant-connect-to-local-mysql-server-through-socket-var-mysql-mysql-sock-38

**Comment by wackejohn** [comment]
I modifed the scripts/config.sh file:
"HOST='localhost'" to "HOST='127.0.0.1'",and it can connect to mysql now.Thanks.
