### ISSUE TITLE
Add iOS to OS list? 

### ISSUE THREAD

**Issue by chasgames** [Chocobozzz/OpenVPN-Admin#39]
Hello

Awesome project :)

How can i add iOS as an operating system, or perhaps add this to the project? I think setenv CLIENT_CERT 0 may be required for ios.

Thanks

**Comment by Chocobozzz** [comment]
Hi!

I'm sorry but I don't have IOS device. 

But your could try to add it in the PHP [here](https://github.com/Chocobozzz/OpenVPN-Admin/blob/master/index.php#L24) and [here](https://github.com/Chocobozzz/OpenVPN-Admin/blob/master/include/html/form/configuration.php#L24). Then, you would just have to add your configuration directory in the [*client-conf* directory](https://github.com/Chocobozzz/OpenVPN-Admin/tree/master/installation/client-conf).

If it works please make a PR :)

**Comment by chasgames** [comment]
Ok Thanks! I'll give that a shot

**Comment by arobase13** [comment]
The topic interests me a lot, I wanted to know how are generated .ovpn files?

Is there a template in the folders?

**Comment by Chocobozzz** [comment]
Yes, in the [windows directory](https://github.com/Chocobozzz/OpenVPN-Admin/blob/master/installation/client-conf/windows/client.ovpn) for example.

**Comment by arobase13** [comment]
Ok, after checking, the ovpn files are configured by install.sh.

So a question, a file sh is it able to put in a variable the contents of a text file for example?
