### ISSUE TITLE
how to setup webserver?

### ISSUE THREAD

**Issue by malikshi** [Chocobozzz/OpenVPN-Admin#41]
![screenshot_158](https://cloud.githubusercontent.com/assets/9080737/24031985/323cd3c0-0b18-11e7-859f-3c2a030a8ab8.png)
please give me some tutorial, i dont know how to setup this

**Comment by Chocobozzz** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-ubuntu-14-04

https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04
