### ISSUE TITLE
Unable to access shared folders

### ISSUE THREAD

**Issue by arobase13** [Chocobozzz/OpenVPN-Admin#43]
I have just installed the script on a server, everything is ok, I have internet on my pc, one of my pc is under Vista (work) and seven at home.

The question is that I can not access my shared folder, I enter the explorer \\ 10.8.0.6 I have nothing, but under seven the network profile is public network.

Is there a setting for iptables?

Thank you
good night

**Comment by Chocobozzz** [comment]
Are you able to ping 10.8.0.6?

**Comment by arobase13** [comment]
Yes I can ping, an iptables problem? A port to open?

**Comment by arobase13** [comment]
Looking good Windows Vista I found that the windows firewall was reactivated.
I have disabled it for testing purposes this seems OK damage though for VPN connection breaks.
