### ISSUE TITLE
Unwanted disconnection

### ISSUE THREAD

**Issue by arobase13** [Chocobozzz/OpenVPN-Admin#45]
Hello, in addition to the problem of access to shared files, here I notice on two pc remote one under Windows Vista and the other under Seven using each openvpn gui v.2.4.0 unwanted disconnection, and those several times By days, in the logs of the clients no error, I have not looked at the server.
Have you ever had such a disconnection problem?

**Comment by Chocobozzz** [comment]
Maybe related to https://github.com/Chocobozzz/OpenVPN-Admin/blob/master/installation/server.conf#L45

**Comment by arobase13** [comment]
Using my Android smartphone with the application openvpn Connect is nearly 4:35 am that I am connected a priori without the slightest disconnections.

Reversing the desktop in Windows Vista is no longer accessible probably disconnect after not even a VPN connection time, I will see to try another VPN client on the Windows workstations.

**Comment by SansPseudoFix** [comment]
I think it's a windows client issue. I haven't issues with my Gnome-shell client, but for instance, my android client have, sometimes, disconnections.

**Comment by arobase13** [comment]
With tunXten under Win 7, the connection is very stable, knowing that with the openvpn clien its disconnect every minute.
