### ISSUE TITLE
Cannot access web-ui

### ISSUE THREAD

**Issue by duramato** [Chocobozzz/OpenVPN-Admin#47]
After running the installer, and accessing `/index.php?installation` , i get an `Internal server error` 

And from apache logs: 
```
[Mon Apr 10 09:04:44.088968 2017] [:error] [pid 1328] [client :34120] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'www-data'@'localhost' (using password: NO)' in /var/www/html/include/connect.php:5\nStack trace:\n#0 /var/www/html/include/connect.php(5): PDO->__construct('mysql:host=loca...', '', '', Array)\n#1 /var/www/html/index.php(5): require('/var/www/html/i...')\n#2 {main}\n  thrown in /var/www/html/include/connect.php on line 5
```

**Comment by duramato** [comment]
Did a OS reinstall, and so as openvpn-admin's and i'm getting

```
[Mon Apr 10 14:33:26.259393 2017] [:error] [pid 20760] [client 95.93.17.6:43526] PHP Warning:  require(/var/www/html/include/functions.php): failed to open stream: Permission denied in /var/www/html/index.php on line 4
[Mon Apr 10 14:33:26.259433 2017] [:error] [pid 20760] [client 95.93.17.6:43526] PHP Fatal error:  require(): Failed opening required '/var/www/html/include/functions.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/index.php on line 4
```

It has permissions to all of the files, i don't know what he doesn't have permission to.

**Comment by Chocobozzz** [comment]
Maybe apache is not able to go in `/var/www/html/include/` directory.

**Comment by mindej** [comment]
try this: sudo chown www-data:www-data /var/www/html -r

**Comment by hamadaDev** [comment]
hi 
can't access ui 
![image](https://cloud.githubusercontent.com/assets/11373077/25776208/106d84ee-32c1-11e7-93f1-c54a244b0024.png)

i think  the error in connected database   

![image](https://cloud.githubusercontent.com/assets/11373077/25776198/c95f88a4-32c0-11e7-8a9d-712880b2b890.png)

**Comment by Chocobozzz** [comment]
@hamadaDev Check your php logs (apache/php-fpm)

**Comment by hamadaDev** [comment]
hi 
it's Solved 
I Reboot the server and make update and it's run now  .
