### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by sbuchb** [Chocobozzz/OpenVPN-Admin#48]
After creating the admin account on the webinterface and afterwards trying to login with it, I get an login error. I deinstalled it several times and installed it again but I always get this messages when trying to login as Administrator.
![vpn-admin_login_error](https://cloud.githubusercontent.com/assets/27730221/25132988/a94f5bda-244b-11e7-92d2-8dab52acca5b.png)

**Comment by Chocobozzz** [comment]
Administrator username is "root"

**Comment by sbuchb** [comment]
I can´t login either to get the configuration files or to login as admin ... I already tried to login as "root"

**Comment by Chocobozzz** [comment]
Administrator can't get configurations, they are just administrators of the web interface. You need to create a user first.

What is the content of your `admin` table? (hide some characters of the `admin_pass` column).

**Comment by sbuchb** [comment]
I cannot access the admin table. I created an admin on the web interface(10.10.31.60/openvpn-admin/index.php?installation) but afterwards I can´t login to it. I installed OpenVPN-Admin on a CentOS 7 computer.

**Comment by Chocobozzz** [comment]
I mean the admin table in mysql.

**Comment by sbuchb** [comment]
It´s empty.

**Comment by Chocobozzz** [comment]
Desinstall the application, check the database is removed and reinstall it with another admin password

**Comment by sbuchb** [comment]
I desinstalled the app, checked if I had to manually delete the database(the db was already deleted) and then installed it again but the db is still empty after I created the admin. 
![error](https://cloud.githubusercontent.com/assets/27730221/25135304/4596fcfe-2452-11e7-954f-53de1ea1e0ee.png
![db](https://cloud.githubusercontent.com/assets/27730221/25135341/680766b6-2452-11e7-8b35-66bc6443896f.png)

**Comment by Chocobozzz** [comment]
Check if you have errors in your webserver (apache/nginx) logs

**Comment by sbuchb** [comment]
[Tue Apr 18 08:41:59.222194 2017] [:error] [pid 30577] [client 10.10.10.182:61357] PHP Warning:  unlink(/var/www/html/openvpn-admin/sql/schema-0.sql): Permission denied in /var/www/html/openvpn-admin/index.php on line 141, referer: http://10.10.31.60/openvpn-admin/index.php?installation
[Tue Apr 18 08:41:59.227131 2017] [:error] [pid 30577] [client 10.10.10.182:61357] PHP Warning:  unlink(/var/www/html/openvpn-admin/sql/schema-5.sql): Permission denied in /var/www/html/openvpn-admin/index.php on line 141, referer: http://10.10.31.60/openvpn-admin/index.php?installation
[Tue Apr 18 08:41:59.227685 2017] [:error] [pid 30577] [client 10.10.10.182:61357] PHP Fatal error:  Call to undefined function password_hash() in /var/www/html/openvpn-admin/include/functions.php on line 38, referer: http://10.10.31.60/openvpn-admin/index.php?installation
[Tue Apr 18 13:31:24.419444 2017] [:error] [pid 30552] [client 10.10.10.182:65133] PHP Warning:  unlink(/var/www/html/openvpn-admin/sql/schema-0.sql): Permission denied in /var/www/html/openvpn-admin/index.php on line 141, referer: http://10.10.31.60/openvpn-admin/index.php?installation
[Tue Apr 18 13:31:24.424525 2017] [:error] [pid 30552] [client 10.10.10.182:65133] PHP Warning:  unlink(/var/www/html/openvpn-admin/sql/schema-5.sql): Permission denied in /var/www/html/openvpn-admin/index.php on line 141, referer: http://10.10.31.60/openvpn-admin/index.php?installation
[Tue Apr 18 13:31:24.424966 2017] [:error] [pid 30552] [client 10.10.10.182:65133] PHP Fatal error:  Call to undefined function password_hash() in /var/www/html/openvpn-admin/include/functions.php on line 38, referer: http://10.10.31.60/openvpn-admin/index.php?installation
[Tue Apr 18 13:55:42.205360 2017] [mpm_prefork:notice] [pid 30549] AH00170: caught SIGWINCH, shutting down gracefully
[Tue Apr 18 13:55:43.260556 2017] [suexec:notice] [pid 9287] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Apr 18 13:55:43.282888 2017] [auth_digest:notice] [pid 9287] AH01757: generating secret for digest authentication ...
[Tue Apr 18 13:55:43.283600 2017] [lbmethod_heartbeat:notice] [pid 9287] AH02282: No slotmem from mod_heartmonitor
[Tue Apr 18 13:55:43.299867 2017] [mpm_prefork:notice] [pid 9287] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Tue Apr 18 13:55:43.299898 2017] [core:notice] [pid 9287] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

**Comment by Chocobozzz** [comment]
You need PHP >= 5.5

https://github.com/Chocobozzz/OpenVPN-Admin#prerequisite
