### ISSUE TITLE
How to use on windows?

### ISSUE THREAD

**Issue by abhinavbalu** [Chocobozzz/OpenVPN-Admin#55]
There is a zip file that is downloaded, and it does not extract on windows, and makes multiple copies of itself on my MacBook. How do you use this on windows?

Also, is there a way to modify this program to let me download ovpn files for the users instead of zip files?

**Comment by SansPseudoFix** [comment]
> How do you use this on windows?

What are you trying to do? Install an openVPN-Admin (ie openVPN **server**) on Windows? [You can't](https://github.com/Chocobozzz/OpenVPN-Admin/#prerequisite):

> Prerequisite
> GNU/Linux with Bash and root access

If you want to use an OpenVPN **client**, you have **plenty** of *how to* on Internet: just search ``how to install openvpn client windows``.

> Also, is there a way to modify this program to let me download ovpn files for the users instead of zip files?

Openvpn files are **in** zip files…

**Comment by abhinavbalu** [comment]
I'm not that stupid.
I set up the whole thing on a debian instance running on GCE.
It all works, but I download the zip files, it does not extract on windows, mac or linux.
I tried using an openvpn windows client that supports zip files, only to receive an "invalid file" error.
Those are my issues right now.
Sorry if it sounded like I meant something else.

**Comment by SansPseudoFix** [comment]
Ok, I misunderstood. We have plenty of users who ask for our help without any search… Sorry.
Your logs don't help?

Client configuration files are in: ``/var/www/html/openvpn-admin/client-conf/windows``.

**Comment by Chocobozzz** [comment]
@abhinavbalu Do you have error in your apache logs? Seems to be a zip creation failure

**Comment by abhinavbalu** [comment]
Here is what I got. I already changed permissions to 777 and changed ownership to root:www-data
If I'm not wrong, it's that PHP does not have permissions to write to the directory. I googled some, but couldn't find much. How do I go about this?

![Screenshot of error log](https://user-images.githubusercontent.com/17591531/27166348-8f84b15c-51b7-11e7-882a-b34202f3d08a.PNG)

**Comment by SansPseudoFix** [comment]
What's your php version?  You need ``PHP >= 5.5.0``.

**Comment by abhinavbalu** [comment]
It's PHP 5.6.30
I created the info.php file so you can view it [here](vpn.abhinavbalu.com/info.php)

**Comment by Chocobozzz** [comment]
Check www-data user can cross /var/www/html and do chown -R www-data:www-data openvpn-admin.
