### ISSUE TITLE
Error add user

### ISSUE THREAD

**Issue by beho1der** [Chocobozzz/OpenVPN-Admin#60]
Install on Ubuntu 16.04 with NGINX + php-fpm 

When i creaate user, i take error:

2017/07/19 11:25:45 [error] 9495#9495: *99 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'openvpn-admin.user' doesn't exist in /var/www/html/openvpn-admin/include/grids.php:127
Stack trace:
#0 /var/www/html/openvpn-admin/include/grids.php(127): PDOStatement->execute(Array)
#1 {main}
  thrown in /var/www/html/openvpn-admin/include/grids.php on line 127" while reading response header from upstream, client: 10.1.1.156, server: _, request: "POST /openvpn-admin/include/grids.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "10.1.1.168", referrer: "http://10.1.1.168/openvpn-admin/index.php?admin"

http://savepic.ru/14896736.png

**Comment by Chocobozzz** [comment]
Did you read this similar issue? https://github.com/Chocobozzz/OpenVPN-Admin/issues/23

**Comment by beho1der** [comment]
Yes, I seem to have the same error when installing for some reason did not create a table

l# mysql -u root -p -e "use openvpn-admin; show tables;"
Enter password: 
+-------------------------+
| Tables_in_openvpn-admin |
+-------------------------+
| admin                   |
| application             |
+-------------------------+
Why this happened and how best to fix it ?

**Comment by Chocobozzz** [comment]
Remove all tables and try to reinstall them -> `http://your-installation/index.php?installation`

**Comment by beho1der** [comment]
I remove all tables on databases and  executed the request http://your-installation/index.php?installation
Received an error: 017/07/20 06:56:53 [error] 9495#9495: *135 FastCGI sent in stderr: "PHP message: PHP Warning:  file_get_contents(/var/www/html/openvpn-admin/sql/schema-0.sql): failed to open stream: No such file or directory in /var/www/html/openvpn-admin/index.php on line 134" while reading response header from upstream, client: 10.1.1.156, server:
I copy сopied folder sql on web server and repeated the request and that's OK, but in databases not tables users and logs
x# mysql -u root -p -e "use openvpn-admin; show tables;"
Enter password: 
+-------------------------+
| Tables_in_openvpn-admin |
+-------------------------+
| admin                   |
| application             |
+-------------------------+

**Comment by modfiles** [comment]
you need to edit your mysql.cfg to accept 00:00:00 as default value to fix that problem
try to read the readme file in my fork of this repo

**Comment by beho1der** [comment]
It works, Big Thanks. This would have to be added to the documentation
