### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by billyprice1** [Chocobozzz/OpenVPN-Admin#61]
./install.sh  base_dir:/var/www/html/ user:root group:nogroup
 cant get it working

**Comment by Chocobozzz** [comment]
`./install.sh /var/www/html/ root nogroup`

But don't install as root, create a specific user.

**Comment by simplecode678** [comment]
./install.sh /var/www/html/ ok i understand this step
do i have to create with sftp under /html/myfolder/
do i have to create folders inside for user and group ?
sorry :(
