### ISSUE TITLE
'scripts/login.sh': No such file or directory

### ISSUE THREAD

**Issue by TacoScheltema** [Chocobozzz/OpenVPN-Admin#63]
Hi,

First of all, thanks for a great product.

after a fresh install following your installation guide I noticed VPN was not running and no log file was created.
I ran openvpn manually like this:
```
openvpn --config /etc/openvpn/server.conf
```
which resulted in a log file (but no running openvpn server)
the log showed this error:
```
Options error: --auth-user-pass-verify script fails with 'scripts/login.sh': No such file or directory
Options error: Please correct this error.
```
I tried a few things to correct it, in the end the most straight-forward fix is as follows;
In the file /etc/default/openvpn, change the line
```
OPTARGS=""
```
to
```
OPTARGS="--chroot /etc/openvpn"
```

Not sure if this could be called a bug, but maybe this can be added in the setup script?

Kind Regards,
Taco

**Comment by Chocobozzz** [comment]
Hi Taco,

Thanks for reporting this issue. But what is your operating system?

**Comment by TacoScheltema** [comment]
Hi, I installed it on a debian 8 system.

**Comment by TacoScheltema** [comment]
I think I worked out what the issue was with openvpn not starting; it's not adding the OPTARGS like I mentioned before but running
```
systemctl daemon-reload
```
which is needed to pick up any changes in the systemctl script.

**Comment by Chocobozzz** [comment]
Thanks!
