### ISSUE TITLE
Documentation for debian9 Stretch

### ISSUE THREAD

**Issue by TacoScheltema** [Chocobozzz/OpenVPN-Admin#64]
Hi,

Here's some setup instructions for debian9:

# Install OpenVPN-Admin on Debian 9 Stretch

## Install nodejs and npm

Due to security issues (see https://www.debian.org/releases/stretch/amd64/release-notes/ch-information.en.html#libv8) node.js should not be installed
from the debian 9 repository. Instead, the following instructions (found here: http://linuxbsdos.com/2017/06/26/how-to-install-node-js-lts-on-debian-9-stretch/)
will help you set up node.js 6.x LTS (long term support) which also provide npm.

Install curl:
```
$ apt-get install curl
```

Setup the required repositories:
```
$ curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
```

Install node.js and npm:
```
$ apt-get install nodejs
```

## Install OpenVPN-Admin

```
$ apt-get install openvpn apache2 php7.0 php7.0-mysql php7.0-zip mariadb-server-10.1 unzip git wget sed
$ npm install -g bower
```

```
$ cd ~/my_coding_workspace
$ git clone https://github.com/Chocobozzz/OpenVPN-Admin openvpn-admin
$ cd openvpn-admin
$ ./install.sh www_base_dir web_user web_group
```

make sure to run the following command so that the openvpn systemctl script is updated;
```
systemctl daemon-reload
```

**Comment by Chocobozzz** [comment]
Thanks!
