### ISSUE TITLE
After installation HTTP ERROR 500

### ISSUE THREAD

**Issue by Ripmaster1990** [Chocobozzz/OpenVPN-Admin#66]
after creating the user when i loging i cant download the config. http error 500

**Comment by SansPseudoFix** [comment]
Can you provide some logs? Apache/nginx and openvpn.

**Comment by Ripmaster1990** [comment]
I habe changed dein PHP 7 zu PHP 5 and now Works. I cant Connect TLS Error....


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: spf <notifications@github.com> Datum: 12.08.17  11:13  (GMT+01:00) An: Chocobozzz/OpenVPN-Admin <OpenVPN-Admin@noreply.github.com> Cc: Ripmaster1990 <ruftec2014@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [Chocobozzz/OpenVPN-Admin] After installation HTTP ERROR 500 (#66) 
Can you provide some logs? Apache/nginx and openvpn.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Chocobozzz/OpenVPN-Admin","title":"Chocobozzz/OpenVPN-Admin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Chocobozzz/OpenVPN-Admin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SansPseudoFix in #66: Can you provide some logs? Apache/nginx and openvpn."}],"action":{"name":"View Issue","url":"https://github.com/Chocobozzz/OpenVPN-Admin/issues/66#issuecomment-321968240"}}}
