### ISSUE TITLE
Configuration file download incomplete from Debian Jessie

### ISSUE THREAD

**Issue by cmivxx** [Chocobozzz/OpenVPN-Admin#68]
All configuration file downloads are incomplete and failing after a successful installation on Debian Jessie.  Any idea why that might be, or where I can look to see what might be up?

**Comment by Chocobozzz** [comment]
Please paste PHP logs.

**Comment by cmivxx** [comment]
Here's the only entries in the PHP error log (fresh install of Apache and PHP):

```
[Wed Aug 16 16:22:45.816060 2017] [:error] [pid 32155] [client 73.202.59.52:60226] PHP Warning:  readfile(./client-conf/openvpn-gnu-linux.zip): failed to open stream: No such file or directory in /var/www/html/openvpn-admin/index.php on line 65, referer: http://162.243.140.98/openvpn-admin/index.php
[Wed Aug 16 16:30:00.619832 2017] [:error] [pid 31802] [client 73.202.59.52:61262] PHP Warning:  readfile(./client-conf/openvpn-gnu-linux.zip): failed to open stream: No such file or directory in /var/www/html/openvpn-admin/index.php on line 65, referer: http://162.243.140.98/openvpn-admin/index.php
[Wed Aug 16 16:58:49.591750 2017] [:error] [pid 31802] [client 73.202.59.52:65401] PHP Warning:  readfile(./client-conf/openvpn-gnu-linux.zip): failed to open stream: No such file or directory in /var/www/html/openvpn-admin/index.php on line 65, referer: http://162.243.140.98/openvpn-admin/index.php
```

**Comment by cmivxx** [comment]
So apparently the folder just needed a `CHMOD` and it was good.  The ZIP is now downloaded correctly.  Are these the 3 docs that are supposed to be downloaded?  What does the update-resolv.sh do and shouldn't there be instructions?

Thank's for taking a look.

<img width="211" alt="screen shot 2017-08-16 at 2 16 36 pm" src="https://user-images.githubusercontent.com/2914978/29385793-e31b55ee-828d-11e7-8741-d86e236cfdb9.png">

**Comment by cmivxx** [comment]
Ok, now after the download of the ZIP, and trying to install to Tunnelblick (on OSX), I get the following error:

<img width="617" alt="screen shot 2017-08-16 at 2 21 56 pm" src="https://user-images.githubusercontent.com/2914978/29385917-68f6a9ca-828e-11e7-9244-589daf43646f.png">

**Comment by Chocobozzz** [comment]
It seems it failed to generate the key at installation step. Try to reinstall and pay attention to potential error logs.

**Comment by cmivxx** [comment]
Yeah, it was indeed an error in the main log that a reinstall fixed.  

I would note that I still have to chmod the web client-files/ folder in order to allow generation of the zip files.  

Also, I'm having a hell of a time getting the VPN to work with your configuration.  I originally followed a DigitalOcean tutorial on how to set up the OpenVPN server, and using the manually generated config (OVPN file), the VPN works fine.  However using the config generated with this server does not.  I'm doing some experimenting now, but you may want to put in some links to a tutorial for setting up OpenVPN that works with your config.

Thanks for the awesome tool!
