### ISSUE TITLE
Getting the last version of EasyRSA

### ISSUE THREAD

**Issue by nikaro** [Chocobozzz/OpenVPN-Admin#7]
Hello,

What do you think about getting the latest version of EasyRSA by getting the version number from GitHUb like this:

```sh
LATEST_VERSION=$(
    curl -s https://api.github.com/repos/OpenVPN/easy-rsa/releases/latest | \
    grep 'tag_name' | \
    awk '{ print $2 }' | \
    sed 's/[,|"|v]//g'
)
```

Since they provide a sig file we can also check the file integrity with its signature, but for the moment i didn't found where/which is the public key with which check the signature…

I used all of this in my script to upgrade nextcloud/owncloud, you can see it here: https://git.karolak.fr/snippets/16

**Comment by Chocobozzz** [comment]
It would be a good idea but if the new EasyRSA version breaks the API there is a risk the OpenVPN-admin installation fails.

**Comment by nikaro** [comment]
Yep that's right.

Alternatively we can try to follow the latest version of a branch (eg. 2.x, 3.x, etc.). Actually, 2.2.2 is the last version of the 2.x branch and there had been no update since 2013 so there is few chance to see an update on it. But it can still be useful if you move on the 3. branch.

In fact i will fork your project and try to make it work with EasyRSA 3.x. Will you accept a pull request if i succeed to do this?

**Comment by Chocobozzz** [comment]
Sure I will.

**Comment by nikaro** [comment]
On which branch should i make my pull request ? master or dev ?

**Comment by Chocobozzz** [comment]
Closed by https://github.com/Chocobozzz/OpenVPN-Admin/pull/15
