### ISSUE TITLE
Just a question about data send/received

### ISSUE THREAD

**Issue by jsknto** [Chocobozzz/OpenVPN-Admin#71]
To get the data send/received in Kb you are dividing by 100, maybe I am missing something somewhere else but, is that division OK, should not be by 1000?

Thank you

**Comment by Chocobozzz** [comment]
Oop's

![http://lutim.cpy.re/aS90eNqP.jpg](http://lutim.cpy.re/aS90eNqP.jpg)

Always thought that these numbers were high. Thans @jsknto, should be fixed.

**Comment by jsknto** [comment]
You're welcome, thanks to you for this great tool!!
