### ISSUE TITLE
Is there a way to automatically merge ca.crt, ta.key and client.ovpn together?

### ISSUE THREAD

**Issue by lyhuuloi** [Chocobozzz/OpenVPN-Admin#72]
* **PHP version:** 5.7
* **MySQL version:** 5.6
* **Webserver (Nginx, Apache...):** Apache
* **What is the expected behaviour?** Automatically merge ca.crt, ta.key and client.ovpn together! 
* **What do you see instead?** A lot of files and it won't compatible with mobile device as default.
* **PHP logs on pastebin:** Nothing.

![image](https://user-images.githubusercontent.com/6936722/29994113-09c2be32-8ff2-11e7-99e6-574fc046a794.png)

**Comment by Chocobozzz** [comment]
Not for yet :)

**Comment by streamcoindev** [comment]
this would be a nice feature :)

**Comment by lagman** [comment]
I've done this on my testing branch.
https://github.com/lagman/OpenVPN-Admin/commit/3f436676ef6964e3cd6729b3a8c372f6bc6b9ac3
https://github.com/lagman/OpenVPN-Admin/commit/1ad7e1de07f64b879badb5f620394dbfe5a55a7d

**Comment by lyhuuloi** [comment]
> I've done this on my testing branch.
> [lagman@3f43667](https://github.com/lagman/OpenVPN-Admin/commit/3f436676ef6964e3cd6729b3a8c372f6bc6b9ac3)
> [lagman@1ad7e1d](https://github.com/lagman/OpenVPN-Admin/commit/1ad7e1de07f64b879badb5f620394dbfe5a55a7d)

Thank you, it's actually work!

**Comment by lagman** [comment]
You're welcome. I'll ask for a pull request then.
