### ISSUE TITLE
ui not support cert auth?

### ISSUE THREAD

**Issue by lannyMa** [Chocobozzz/OpenVPN-Admin#74]
- your ui now just support  username and password auth?
i add an user lanny,and i download the config zip via ui.i got those files. is this right?
![](http://ww1.sinaimg.cn/large/9e792b8fgy1fjh6rw4wkyj20nb0f4wh5)

- meanwhile i find the ccd dir is still empty 
![](http://ww1.sinaimg.cn/large/9e792b8fgy1fjh6waeyssj20h302e3yg)

**Comment by Chocobozzz** [comment]
* Right
 * We don't use client config directory 

Yes, we only support username/password auth.
