### ISSUE TITLE
Statistics web ui

### ISSUE THREAD

**Issue by Madji** [Chocobozzz/OpenVPN-Admin#76]
* **PHP version: PHP 5.6.30-0+deb8u1
* **MySQL version: 5.5.57-0+deb8u1
* **Webserver Apache.

Statistics transferred to accepted not check. always 0
else works fine. Thanks!
![1](https://user-images.githubusercontent.com/2238714/30702140-cf7d57e8-9ef4-11e7-9261-4e129fa8657c.png)

**Comment by Chocobozzz** [comment]
Receveid/Sent are set when the client disconnects

**Comment by Madji** [comment]
No. firstly, not running off time. and after disabling client statistics are not changed
