### ISSUE TITLE
base_dir: The place where the web application will be put in

### ISSUE THREAD

**Issue by rexzerox** [Chocobozzz/OpenVPN-Admin#77]
base_dir: The place where the web application will be put in
        user:     User of the web application
        group:    Group of the web application
![screenshot_332](https://user-images.githubusercontent.com/30548067/30948051-f10c5e40-a43f-11e7-8eee-dc527438390e.png)

please help how to fix i dont know to get rid of it

**Comment by rexzerox** [comment]
please give me an example  i really dont know what dir to put on it @Chocobozzz

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/OpenVPN-Admin/issues/61
