### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by assistenzaremoto** [Chocobozzz/OpenVPN-Admin#80]
* **PHP version:**
* **MySQL version:**
* **Webserver (Nginx, Apache...):**
* **What is the expected behaviour?**
* **What do you see instead?**
* **PHP logs on pastebin:**
![image](https://user-images.githubusercontent.com/18951137/33048733-b09b6602-ce5c-11e7-899b-691919492a82.png)

**Comment by Chocobozzz** [comment]
Fill the template.
