### ISSUE TITLE
is this still working?

### ISSUE THREAD

**Issue by capiazmi** [Chocobozzz/OpenVPN-Admin#81]
my system :
centos 7,
nginx,
php 7.
when login, i redirected to login form and nothing else happen.

**Comment by Chocobozzz** [comment]
Miss the logs.

**Comment by capiazmi** [comment]
when i login with the correct username and passwd for admin, it redirect me to openvpn-admin/index.php?admin, when i put incorrect passwd, it return error just fine.
when i get into the code,i disable 
**header("Location: index.php?admin");
      exit(-1);**
in this line.
if($data && passEqual($_POST['admin_pass'], $data['admin_pass'])) {
      $_SESSION['admin_id'] = $data['admin_id'];
    }
only then i can see the admin page just fine, but i fail on create user or anything.

**Comment by capiazmi** [comment]
ok, i fix it, seems mis configuration with my php.
