### ISSUE TITLE
./install.sh www_base_dir web_user web_group : explaination

### ISSUE THREAD

**Issue by simplecode678** [Chocobozzz/OpenVPN-Admin#84]
Hi !
Sorry new to vpn and debian this is what i have done
apt-get update
apt-get install openvpn apache2 php5-mysql mysql-server php5 nodejs unzip git wget sed npm curl
npm install -g bower
cd ~/(i have created my folder with sftp)
git clone https://github.com/Chocobozzz/OpenVPN-Admin openvpn-admin
cd openvpn-admin
./install.sh www_base_dir web_user web_group
And i do not understand this step, can anyone please let me know exactly what to do ?
Thanks !

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/OpenVPN-Admin/issues/61
