### ISSUE TITLE
Miss node

### ISSUE THREAD

**Issue by Bary92** [Chocobozzz/OpenVPN-Admin#85]
Hello, I made a debian installation 8 jessie but when I do ./install.sh / var / www / html username and group, the console shows me Miss node, can you help me 'please? sorry for english

**Comment by Chocobozzz** [comment]
You need to install `bower` that requires `nodejs`: https://github.com/Chocobozzz/OpenVPN-Admin#prerequisite

**Comment by Bary92** [comment]
Thank you
