### ISSUE TITLE
PHP Error on index.php

### ISSUE THREAD

**Issue by afrat** [Chocobozzz/OpenVPN-Admin#87]
* **PHP version:**
php7.0
* **MySQL version:**
mysql 5.7.20
* **Webserver (Nginx, Apache...):**
apache2
* **What is the expected behaviour?**
Not showing php code in browser.
* **What do you see instead?**
PHP code in the browser.
* **PHP logs on pastebin:**
No Errors in php log.

![vpn_admin_error](https://user-images.githubusercontent.com/32166052/34781348-e2dde068-f625-11e7-801d-b99ab1e14bdf.png)

**Comment by Chocobozzz** [comment]
It's an issue with your webserver configuration, not a openvpn-admin bug.
