### ISSUE TITLE
Installation Failure on Centos7 Apache-HTTPD

### ISSUE THREAD

**Issue by chitenderkumar** [Chocobozzz/OpenVPN-Admin#97]
* **PHP version:5.4**
* **MySQL version:5.5.56-2**
* **Webserver (Nginx, Apache...):Apache-Httpd**

* **What is the expected behaviour?**
post configuring the admin username/password, it should lend on another step.
* **What do you see instead?**
post entering the username/password i am getting `http 500` error in web response.

* **PHP logs on pastebin:**
[Sun Mar 25 05:04:02.605592 2018] [:error] [pid 2002] [client 160.202.36.199:38668] PHP Fatal error:  Call to undefined function password_hash() in /var/www/html/openvpn-admin/include/functions.php on line 38, referer: http://18.220.202.223/openvpn-admin/index.php?installation

**Comment by chitenderkumar** [comment]
so, shall i upgrade my PHP to 5.7?

**Comment by Chocobozzz** [comment]
yep
