### ISSUE TITLE
/etc/openvpn/server.conf:83: verify-client-cert (2.3.2)

### ISSUE THREAD

**Issue by assistenzaremoto** [Chocobozzz/OpenVPN-Admin#98]
installation on ubuntu 14.04 with apache 2 mmi from this error Unrecognized option or missing parameter (s) in /etc/openvpn/server.conf:83: verify-client-cert (2.3.2) how can I fix it is a little bit

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/OpenVPN-Admin/issues/82
